### ISSUE TITLE
attribute 'visible' not working in version 1.7.3

### ISSUE THREAD

**Issue by stjcottbus** [kartik-v/yii2-detail-view#92]
I'm using attributes with 'visible' set to false which I only need as form-fields but not visible to users.
This leads to:

PHP Notice yii\base\ErrorException with message 
Undefined variable: i in .. vendor/kartik-v/yii2-detail-view/DetailView.php:1076

(I'm getting 1.7.3 with composer, not 1.7.4)

Is this a known issue or am I doing something wrong

**Comment by stjcottbus** [comment]
Ignore it. Solved in 1.7.4

**Comment by vadim-bulochnik** [comment]
But version 1.7.4 still not released. I've tried with "dev-master" version, but 'visible' attribute still not works.
